import { type NextPage } from "next";
import Head from "next/head";
import { IndividualNft } from "~/modules/common/section/individual-nft";

const NftId: NextPage = () => {
  return (
    <>
      <Head>
        <title>NFT | EXPLORE</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IndividualNft />
    </>
  );
};

export default NftId;
