import { type NextPage } from "next";
import Head from "next/head";
import { CreateNftForm, Hero } from "~/modules/common/section/create-nft";

const CreateNft: NextPage = () => {
  return (
    <>
      <Head>
        <title>NFT | Create Nft</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <CreateNftForm />
    </>
  );
};

export default CreateNft;
