import { type NextPage } from "next";
import Head from "next/head";
import { MyDashboard } from "~/modules/common/section/dashboard";

const Dashboard: NextPage = () => {
  return (
    <>
      <Head>
        <title>NFT | My Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyDashboard />
    </>
  );
};

export default Dashboard;
