import { type NextPage } from "next";
import Head from "next/head";
import { Hero, How, NewItems } from "~/modules/common/section/home";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>NFT Bay</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <How />
      <NewItems />
    </>
  );
};

export default Home;
